{
 "title": "5189 Bundler",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "chain_id", "label": "Chain ID", "query": { "query": "label_values(chain_id)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(bundler_mempool_known,id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (transport) (bundler_libp2p_swarm_connections_opened_total{chain_id=\"$chain_id\", id=\"$instance\"}) - sum by (transport) (bundler_libp2p_swarm_connections_closed_total{chain_id=\"$chain_id\", id=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bootnodes",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bundler_p2p_bootnodes_connected{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Connected"
    },
    {
     "expr": "bundler_p2p_bootnodes_failed{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "bundler_p2p_bootnodes_retries{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Retries"
    }
   ]
  },
  {
   "title": "Pubsub Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "increase(bundler_p2p_broadcast_sent_bytes_count{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval]) * -1",
     "legendFormat": "Sent {{type}}"
    },
    {
     "expr": "increase(bundler_p2p_pubsub_received_bytes_count{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Received {{type}}"
    }
   ]
  },
  {
   "title": "Pubsub Datarate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bundler_p2p_broadcast_sent_bytes_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) * -1",
     "legendFormat": "Sent {{type}}"
    },
    {
     "expr": "rate(bundler_p2p_pubsub_received_bytes_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "Received {{type}}"
    }
   ]
  },
  {
   "title": "Pubsub Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bundler_p2p_pubsub_received_bytes_count{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Received {{type}}"
    },
    {
     "expr": "bundler_p2p_broadcast_sent_bytes_count{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Sent {{type}}"
    }
   ]
  },
  {
   "title": "Dial Errors",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bundler_libp2p_swarm_dial_errors_total{chain_id=\"$chain_id\", id=\"$instance\"}[$__range])) by (error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 14 },
   "targets": [
    {
     "expr": "sum (rate(bundler_libp2p_swarm_connections_opened_total{dir=\"outbound\",chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])) by (transport, security, muxer)",
     "legendFormat": "Outbound {{transport}} {{security}} {{muxer}}"
    },
    {
     "expr": "sum (rate(bundler_libp2p_swarm_connections_opened_total{dir=\"inbound\",chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])) by (transport, security, muxer) * -1",
     "legendFormat": "Inbound {{transport}} {{security}} {{muxer}}"
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Mempool",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bundler_mempool_ops{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Mempool Ops"
    },
    {
     "expr": "bundler_mempool_reserved{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "bundler_mempool_known{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Known Ops"
    }
   ]
  },
  {
   "title": "Mempool composition",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bundler_mempool_ops{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Ops"
    },
    {
     "expr": "bundler_mempool_reserved{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Reserved ops"
    },
    {
     "expr": "bundler_mempool_known{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Known ops"
    }
   ]
  },
  {
   "title": "Mempool in/outs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(bundler_mempool_ops_discarded_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval]) * -1",
     "legendFormat": "Discarded"
    },
    {
     "expr": "increase(bundler_mempool_op_added_time_count{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Added"
    },
    {
     "expr": "increase(bundler_mempool_ops_evicted_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval]) * -1",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Mempool rejects",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(bundler_mempool_ops_rejected_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Rejected {{reason}}"
    }
   ]
  },
  {
   "title": "Mempool forgetting",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(bundler_mempool_ops_forgotten_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Forgotten"
    },
    {
     "expr": "increase(bundler_mempool_ops_marked_for_forget_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Marked for forget"
    }
   ]
  },
  {
   "title": "Mempool  Lifecycles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(bundler_mempool_op_lifetime_sum{chain_id=\"$chain_id\", id=\"$instance\"}[10m]) / rate(bundler_mempool_op_lifetime_count{chain_id=\"$chain_id\", id=\"$instance\"}[10m])",
     "legendFormat": "10m"
    },
    {
     "expr": "rate(bundler_mempool_op_lifetime_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) / rate(bundler_mempool_op_lifetime_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(bundler_mempool_op_lifetime_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1h]) / rate(bundler_mempool_op_lifetime_count{chain_id=\"$chain_id\", id=\"$instance\"}[1h])",
     "legendFormat": "60m"
    }
   ]
  },
  {
   "title": "Partitioner Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 43 },
   "targets": [
    {
     "expr": "bundler_mempool_partitioner_partially_filled_dependencies{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Partially filled dependencies"
    },
    {
     "expr": "bundler_mempool_partitioner_full_dependencies{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Full dependencies"
    },
    {
     "expr": "bundler_mempool_partitioner_known_ops{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Known Operations"
    }
   ]
  },
  {
   "title": "Mempool - Time reserving Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(bundler_mempool_do_reserve_ops_time_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m])/rate(bundler_mempool_do_reserve_ops_time_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "1m avg"
    },
    {
     "expr": "rate(bundler_mempool_do_reserve_ops_time_sum{chain_id=\"$chain_id\", id=\"$instance\"}[10m])/rate(bundler_mempool_do_reserve_ops_time_count{chain_id=\"$chain_id\", id=\"$instance\"}[10m])",
     "legendFormat": "10m avg"
    },
    {
     "expr": "rate(bundler_mempool_do_reserve_ops_time_sum{chain_id=\"$chain_id\", id=\"$instance\"}[24h])/rate(bundler_mempool_do_reserve_ops_time_count{chain_id=\"$chain_id\", id=\"$instance\"}[24h])",
     "legendFormat": "24hs avg"
    }
   ]
  },
  {
   "title": "Partitioner Collisions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 51 },
   "targets": [
    {
     "expr": "rate(bundler_mempool_partitioner_wildcard_collisions_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "Wildcard collisions"
    },
    {
     "expr": "rate(bundler_mempool_partitioner_known_collisions_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "Known collisions"
    },
    {
     "expr": "rate(bundler_mempool_partitioner_overlap_collisions_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "Overlap collisions"
    }
   ]
  },
  {
   "title": "Mempool - Reserve timings",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(bundler_mempool_do_reserve_ops_time_bucket[$__range])) by (le)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Mempool lifetime",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 56 },
   "targets": [
    {
     "expr": "sum(increase(bundler_mempool_op_lifetime_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Avg. Time per RPC call",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(bundler_rpc_method_time_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) / rate(bundler_rpc_method_time_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "1m {{method}}"
    },
    {
     "expr": "rate(bundler_rpc_method_time_sum{chain_id=\"$chain_id\", id=\"$instance\"}[60m]) / rate(bundler_rpc_method_time_count{chain_id=\"$chain_id\", id=\"$instance\"}[60m])",
     "legendFormat": "60m {{method}}"
    }
   ]
  },
  {
   "title": "RPC calls /s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 7, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "req/m" } },
   "targets": [
    {
     "expr": "increase(bundler_rpc_method_time_count{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Sender",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bundler_sender_executed_ops{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Executed Ops"
    },
    {
     "expr": "bundler_sender_chilled_ops{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Chilled Ops"
    }
   ]
  },
  {
   "title": "Endorser totals",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bundler_endorser_is_operation_ready_attempts{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Attempts"
    },
    {
     "expr": "bundler_endorser_is_operation_ready_debugger{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Debugger"
    },
    {
     "expr": "bundler_endorser_is_operation_ready_error{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Errors"
    },
    {
     "expr": "bundler_endorser_is_operation_ready_reverts{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Reverts"
    },
    {
     "expr": "bundler_endorser_is_operation_ready_true_sum{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "True"
    },
    {
     "expr": "bundler_endorser_is_operation_ready_false_sum{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "False"
    }
   ]
  },
  {
   "title": "BaseFee",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 7, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "gwei" } },
   "targets": [
    {
     "expr": "bundler_collector_base_fee{chain_id=\"$chain_id\", id=\"$instance\"} / (100000000)",
     "legendFormat": "BaseFee"
    }
   ]
  },
  {
   "title": "IPFS Totals",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bundler_ipfs_reported_bytes_sum{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "IPFS Upload"
    },
    {
     "expr": "bundler_ipfs_reported_bytes_count{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "IPFS Objects"
    }
   ]
  },
  {
   "title": "Collector - Chain read / avg time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(bundler_collector_fetch_base_fee_duration_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) / rate(bundler_collector_fetch_base_fee_duration_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "BaseFee"
    },
    {
     "expr": "rate(bundler_uniswap_v2_fetch_reserves_time_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) / rate(bundler_uniswap_v2_fetch_reserves_time_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "Uniswap v2 Pool {{pool}}"
    }
   ]
  },
  {
   "title": "IPFS Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(bundler_ipfs_reported_bytes_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "IPFS Upload"
    },
    {
     "expr": "rate(bundler_ipfs_reported_bytes_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "IPFS Objects"
    }
   ]
  },
  {
   "title": "Exchange Rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 91 },
   "targets": [
    {
     "expr": "bundler_uniswap_v2_rate{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Uniswap V2 {{pool}}"
    }
   ]
  },
  {
   "title": "Memory / CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bundler_process_resident_memory_bytes{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "rate(bundler_process_cpu_seconds_total{chain_id=\"$chain_id\", id=\"$instance\"}[60s])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Found Peers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "bundler_p2p_found_peers{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Seen Peers"
    },
    {
     "expr": "bundler_p2p_found_peers_connected{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "bundler_p2p_found_peers_failed_connect{chain_id=\"$chain_id\", id=\"$instance\"}",
     "legendFormat": "Failed connect Peers"
    }
   ]
  },
  {
   "title": "Pruner activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(bundler_pruner_stale_dropped_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Stale dropped"
    },
    {
     "expr": "increase(bundler_pruner_stale_failed_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Failed stale prune {{reason}}"
    },
    {
     "expr": "increase(bundler_pruner_stale_released_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Released"
    }
   ]
  },
  {
   "title": "Pruner runs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(bundler_pruner_banned_time_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) / rate(bundler_pruner_banned_time_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "Time banned"
    },
    {
     "expr": "rate(bundler_pruner_stale_time_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) / rate(bundler_pruner_stale_time_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "Time stale per op"
    },
    {
     "expr": "rate(bundler_pruner_stale_empty_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "Empty runs"
    }
   ]
  },
  {
   "title": "Endorser Timings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 7, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(bundler_endorser_is_operation_ready_duration_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) / rate(bundler_endorser_is_operation_ready_duration_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "isOperationReady"
    },
    {
     "expr": "rate(bundler_endorser_is_operation_debug_ready_duration_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) / rate(bundler_endorser_is_operation_debug_ready_duration_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "isOperationReady (debug)"
    },
    {
     "expr": "rate(bundler_endorser_constraint_met_duration_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) / rate(bundler_endorser_constraint_met_duration_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "constraintMet (1)"
    },
    {
     "expr": "rate(bundler_endorser_constraints_met_duration_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) / rate(bundler_endorser_constraints_met_duration_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "constraintMet (op)"
    },
    {
     "expr": "rate(bundler_endorser_dependency_slot_duration_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) / rate(bundler_endorser_dependency_slot_duration_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "dependency slot"
    },
    {
     "expr": "rate(bundler_endorser_dependency_state_duration_sum{chain_id=\"$chain_id\", id=\"$instance\"}[1m]) / rate(bundler_endorser_dependency_state_duration_count{chain_id=\"$chain_id\", id=\"$instance\"}[1m])",
     "legendFormat": "dependency state"
    }
   ]
  },
  {
   "title": "Endorser Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(bundler_endorser_is_operation_ready_error{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "IsOperationReady error"
    },
    {
     "expr": "increase(bundler_endorser_is_operation_ready_true_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "isOperationReady true"
    },
    {
     "expr": "increase(bundler_endorser_is_operation_ready_false_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "isOperationReady false"
    },
    {
     "expr": "increase(bundler_endorser_is_operation_ready_wildcards_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "isOperationReady wildcards"
    },
    {
     "expr": "increase(bundler_endorser_dependency_state_error_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "dependencyState error {{reason}}"
    },
    {
     "expr": "increase(bundler_endorser_dependency_state_duration_count{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Dependency state"
    },
    {
     "expr": "increase(bundler_endorser_constraints_met_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Constraints met"
    },
    {
     "expr": "irate(bundler_endorser_constraints_not_met{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Constraints not met"
    },
    {
     "expr": "irate(bundler_endorser_constraints_met_error_sum{chain_id=\"$chain_id\", id=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Constraints met error"
    }
   ]
  }
 ]
}